### PR TITLE
added utils library

### PR DESCRIPTION
**Pull request by wcgrizolli**
* Added several utility functions.
    - Highlights: plot_profile, crop_matrix_at_indexes, dummy_images, crop_graphic, load_ini_file.

* Added speckle tracking
    - It includes multi core using the multiprocessing library;

* Added example of speckle tracking in doc/demo.

### CODE REVIEW

**Comment by decarlof** [comment]
@wcgrizolli does the docs build locally? shall I try to build on read the docs?

**Comment by wcgrizolli** [comment]
Yes it builds locally. The server try to build it automatically?

**Comment by data-exchange** [comment]
@wcgrizolli yes the server builds automatically every time a new  version is on the wavepy master. It did it once this pull request was accepted but there are errors and all API links are not showing. I will try to fix it directly on the master.

**Comment by decarlof** [comment]
@wcgrizolli ok now link to API functions build correctly on the readthedocs (see [APIs](https://wavepy.readthedocs.io/en/latest/source/api/wavepy.utils.html)).

**Comment by wcgrizolli** [comment]
@decarlof Great! Looks good

**Pull request merged**
