### PR TITLE
pushing developments to main branch

### PR DESCRIPTION
**Pull request by wcgrizolli**

### CODE REVIEW

**Comment by decarlof** [comment]
@wcgrizolli nice!

**Comment by decarlof** [comment]
@wcgrizolli readthedocs fails to link the functions described in the API (see [api](http://wavepy.readthedocs.io/en/latest/source/api.html)). Are you still working on it or do you want me to have a look?

**Comment by wcgrizolli** [comment]
@decarlof I'm still working on this, so for now lets keep like that. I'll need help at some point with the readthedocs and I'll let you know when I get at that

**Comment by decarlof** [comment]
@ok

**Pull request merged**
